In [1]:
import numpy as np
import torch
import torch.nn as nn

# Khởi tạo Tensor

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [4]:
x_ones = torch.ones_like(x_data)  # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones}")

x_rand = torch.rand_like(x_data, dtype=torch.float)  # overrides the datatype of x_data
print(f"\nRandom Tensor: \n {x_rand}")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]])

Random Tensor: 
 tensor([[0.5474, 0.7187],
        [0.0911, 0.4360]])


In [5]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0269, 0.2381, 0.1505],
        [0.1844, 0.4419, 0.8803]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
tensor = torch.rand(3, 4)

print(tensor)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

tensor([[0.9259, 0.6655, 0.9481, 0.2133],
        [0.3388, 0.2886, 0.7869, 0.2455],
        [0.5542, 0.5685, 0.0536, 0.5490]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Các phép toán trên Tensor

In [7]:
print(x_data)
print(x_data.dtype)
print(x_data.shape)
print(x_data.device)

tensor([[1, 2],
        [3, 4]])
torch.int64
torch.Size([2, 2])
cpu


In [8]:
tensor_sum = x_data + x_data
print(tensor_sum)

tensor([[2, 4],
        [6, 8]])


In [9]:
tensor_prod = 5 * x_data
print(tensor_prod)

tensor([[ 5, 10],
        [15, 20]])


In [10]:
print(f"Tensor:\n {x_data}")
print(f"Transpose tensor:\n {x_data.T}")

tensor_prod_trans = x_data @ x_data.T
print(f"Result:\n {tensor_prod_trans}")

Tensor:
 tensor([[1, 2],
        [3, 4]])
Transpose tensor:
 tensor([[1, 3],
        [2, 4]])
Result:
 tensor([[ 5, 11],
        [11, 25]])


# Indexing and Slicing

In [11]:
first_row = x_data[0]
print(f"First row: {first_row}")
second_col = x_data[:, 1]
print(f"Second column: {second_col}")
value = x_data[1, 1]
print(f"Value: {value}")

First row: tensor([1, 2])
Second column: tensor([2, 4])
Value: 4


# Thay đổi hình dạng Tensor

In [12]:
X = torch.rand(4, 4)
print(f"Random tensor:\n {X}")
Y = X.reshape((16, 1))
print(f"Reshape tensor:\n {Y}")

Random tensor:
 tensor([[0.1133, 0.1437, 0.4758, 0.2063],
        [0.5549, 0.0097, 0.4989, 0.8036],
        [0.5132, 0.6566, 0.6140, 0.8985],
        [0.4468, 0.1644, 0.9430, 0.7941]])
Reshape tensor:
 tensor([[0.1133],
        [0.1437],
        [0.4758],
        [0.2063],
        [0.5549],
        [0.0097],
        [0.4989],
        [0.8036],
        [0.5132],
        [0.6566],
        [0.6140],
        [0.8985],
        [0.4468],
        [0.1644],
        [0.9430],
        [0.7941]])


# Tự động tính Đạo hàm với `autograd`

In [13]:
x = torch.ones(1, requires_grad=True)
print(f"x: {x}")

y = x + 2
print(f"y: {y}")
print(f"y.grad_fn: {y.grad_fn}")

z = 3 * y * y
z.backward()
print(f"Đạo hàm của z theo x: {x.grad}")

x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>)
y.grad_fn: <AddBackward0 object at 0x7b2b8d7b01c0>
Đạo hàm của z theo x: tensor([18.])


In [14]:
input = torch.ones(5)  # input tensor
label = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
pred = torch.matmul(input, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(pred, label)

In [15]:
print(f"Input:\n {input}")
print(f"Label:\n {label}")
print(f"Parmeters:\n {w}")
print(f"Bias:\n {b}")
print(f"Prediction:\n {pred}")
print(f"Loss: {loss}")

Input:
 tensor([1., 1., 1., 1., 1.])
Label:
 tensor([0., 0., 0.])
Parmeters:
 tensor([[ 0.6180,  0.7574,  0.5754],
        [ 0.1068,  0.4342, -0.5988],
        [ 1.6994, -0.7336, -0.1123],
        [ 1.3854,  1.3667,  0.1681],
        [ 1.2387,  1.3280, -0.3087]], requires_grad=True)
Bias:
 tensor([-2.8008, -0.8655,  0.4131], requires_grad=True)
Prediction:
 tensor([2.2475, 2.2873, 0.1367], grad_fn=<AddBackward0>)
Loss: 1.8319182395935059


In [16]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <MulBackward0 object at 0x7b2b8d7b2770>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x7b2a3afae9b0>


In [17]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.3015, 0.3026, 0.1780],
        [0.3015, 0.3026, 0.1780],
        [0.3015, 0.3026, 0.1780],
        [0.3015, 0.3026, 0.1780],
        [0.3015, 0.3026, 0.1780]])
tensor([0.3015, 0.3026, 0.1780])


# Xây dựng Mô hình đầu tiên với `torch.nn`

In [18]:
linear_layer = nn.Linear(in_features=5, out_features=2)
input_tensor = torch.randn(3, 5)
output = linear_layer(input_tensor)

print(f"Input tensor:\n {input_tensor}")
print(f"Input tensor shape: {input_tensor.shape}")

print(f"\nLinear layer: {linear_layer}")
print(f"Linear layer weight: {linear_layer.weight}")
print(f"Linear layer bias: {linear_layer.bias}")

print(f"\nOutput tensor:\n {output}")

Input tensor:
 tensor([[-0.0357,  0.0322, -0.4477,  1.7809, -0.4519],
        [-1.2947,  0.4796, -1.4674, -0.6921, -0.9509],
        [-0.8324,  1.9692, -0.0244, -0.3308, -0.8285]])
Input tensor shape: torch.Size([3, 5])

Linear layer: Linear(in_features=5, out_features=2, bias=True)
Linear layer weight: Parameter containing:
tensor([[ 0.2077, -0.0952,  0.3542,  0.0226, -0.1164],
        [ 0.0853,  0.1652, -0.0875, -0.2548,  0.3096]], requires_grad=True)
Linear layer bias: Parameter containing:
tensor([0.2826, 0.1163], requires_grad=True)

Output tensor:
 tensor([[ 0.2063, -0.4359],
        [-0.4567,  0.0954],
        [ 0.0025,  0.2005]], grad_fn=<AddmmBackward0>)


In [19]:
embedding_layer = nn.Embedding(num_embeddings=10, embedding_dim=3)
input_indices = torch.LongTensor([1, 5, 0, 8])
embeddings = embedding_layer(input_indices)

print(f"Input indices:\n {input_indices}")
print(f"Input tensor shape: {input_indices.shape}")

print(f"\nEmbedding layer: {embedding_layer}")
print(f"Linear layer weight: {embedding_layer.weight}")

print(f"\nOutput embedding:\n {embeddings}")

Input indices:
 tensor([1, 5, 0, 8])
Input tensor shape: torch.Size([4])

Embedding layer: Embedding(10, 3)
Linear layer weight: Parameter containing:
tensor([[-1.1903,  0.9506,  0.7863],
        [ 0.9045, -0.1981, -0.3599],
        [-0.2227,  0.0022,  0.7792],
        [-0.9901, -0.0052, -0.1831],
        [-0.8967,  0.7506, -0.9398],
        [-0.2036,  1.1463, -0.3541],
        [ 0.7286, -0.0745, -1.6800],
        [-0.1031,  0.9848, -1.7614],
        [-0.9449,  1.1879,  0.8034],
        [ 1.9374,  0.1001,  0.9170]], requires_grad=True)

Output embedding:
 tensor([[ 0.9045, -0.1981, -0.3599],
        [-0.2036,  1.1463, -0.3541],
        [-1.1903,  0.9506,  0.7863],
        [-0.9449,  1.1879,  0.8034]], grad_fn=<EmbeddingBackward0>)


In [20]:
class MyEmbeddingModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(MyEmbeddingModel, self).__init__()
        self.embedding = nn.Embedding(num_embeddings=vocab_size, embedding_dim=embedding_dim)
        self.linear = nn.Linear(in_features=embedding_dim, out_features=hidden_dim)
        self.relu = nn.ReLU()
        self.output = nn.Linear(in_features=hidden_dim, out_features=output_dim)

    def forward(self, x):
        embedded = self.embedding(x)
        hiddens = self.relu(self.linear(embedded))
        output = self.output(hiddens)
        return output


model = MyEmbeddingModel(vocab_size=100, embedding_dim=16, hidden_dim=8, output_dim=2)
input_data = torch.LongTensor([[1, 2, 5, 9]])  # một câu gồm 4 từ
output_data = model(input_data)

print(f"Model architecture:\n {model}")
print(f"\nEmbedding layer weight:\n {model.embedding.weight}")
print(f"\n Linear layer weight:\n {model.linear.weight}")
print(f"\n Linear layer bias:\n {model.linear.bias}")
print(f"\nOutput layer weight:\n {model.output.weight}")
print(f"\nOutput layer bias:\n {model.output.bias}")

Model architecture:
 MyEmbeddingModel(
  (embedding): Embedding(100, 16)
  (linear): Linear(in_features=16, out_features=8, bias=True)
  (relu): ReLU()
  (output): Linear(in_features=8, out_features=2, bias=True)
)

Embedding layer weight:
 Parameter containing:
tensor([[ 0.6946,  0.1798,  1.6444,  ...,  0.2180,  0.5779, -1.3023],
        [-1.3901,  0.8253,  0.2276,  ...,  1.7043, -0.4909, -0.3547],
        [ 0.6007,  0.7946,  0.4335,  ..., -0.9407,  0.6403,  1.5879],
        ...,
        [ 1.2256, -0.9045,  1.6420,  ...,  0.2342, -1.5155,  0.2022],
        [ 0.6981, -0.9329,  1.1856,  ..., -1.6669,  0.4777,  0.1773],
        [ 0.9881, -0.9919, -2.2174,  ...,  0.5627, -0.3794,  0.2262]],
       requires_grad=True)

 Linear layer weight:
 Parameter containing:
tensor([[ 0.1249,  0.1644,  0.2135, -0.1289,  0.1772,  0.1038, -0.0555, -0.0770,
          0.1769, -0.0203, -0.1169,  0.0736,  0.0907,  0.1431,  0.1695,  0.0891],
        [-0.0776, -0.0159,  0.1420, -0.1121,  0.2221,  0.2009, -0.1

In [21]:
print(f"\nInput data: {input_data}")
print(f"Input data shape: {input_data.shape}")
print(f"Output data:\n {output_data}")
print(f"Model output shape: {output_data.shape}")


Input data: tensor([[1, 2, 5, 9]])
Input data shape: torch.Size([1, 4])
Output data:
 tensor([[[ 0.1911, -0.4787],
         [-0.3861, -0.6195],
         [ 0.1055, -0.4235],
         [-0.3616, -0.6898]]], grad_fn=<ViewBackward0>)
Model output shape: torch.Size([1, 4, 2])
