In [1]:
import numpy as np
import torch
import torch.nn as nn

# Khởi tạo Tensor

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [4]:
x_ones = torch.ones_like(x_data)  # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones}")

x_rand = torch.rand_like(x_data, dtype=torch.float)  # overrides the datatype of x_data
print(f"\nRandom Tensor: \n {x_rand}")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]])

Random Tensor: 
 tensor([[0.6648, 0.5579],
        [0.7026, 0.1789]])


In [5]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5579, 0.4086, 0.4481],
        [0.8122, 0.9803, 0.8580]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
tensor = torch.rand(3, 4)

print(tensor)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

tensor([[0.5897, 0.3778, 0.5297, 0.0513],
        [0.8316, 0.0781, 0.0156, 0.0608],
        [0.0208, 0.5368, 0.3880, 0.9420]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Các phép toán trên Tensor

In [7]:
print(x_data)
print(x_data.dtype)
print(x_data.shape)
print(x_data.device)

tensor([[1, 2],
        [3, 4]])
torch.int64
torch.Size([2, 2])
cpu


In [8]:
tensor_sum = x_data + x_data
print(tensor_sum)

tensor([[2, 4],
        [6, 8]])


In [9]:
tensor_prod = 5 * x_data
print(tensor_prod)

tensor([[ 5, 10],
        [15, 20]])


In [10]:
print(f"Tensor:\n {x_data}")
print(f"Transpose tensor:\n {x_data.T}")

tensor_prod_trans = x_data @ x_data.T
print(f"Result:\n {tensor_prod_trans}")

Tensor:
 tensor([[1, 2],
        [3, 4]])
Transpose tensor:
 tensor([[1, 3],
        [2, 4]])
Result:
 tensor([[ 5, 11],
        [11, 25]])


# Indexing and Slicing

In [11]:
first_row = x_data[0]
print(f"First row: {first_row}")
second_col = x_data[:, 1]
print(f"Second column: {second_col}")
value = x_data[1, 1]
print(f"Value: {value}")

First row: tensor([1, 2])
Second column: tensor([2, 4])
Value: 4


# Thay đổi hình dạng Tensor

In [12]:
X = torch.rand(4, 4)
print(f"Random tensor:\n {X}")
Y = X.reshape((16, 1))
print(f"Reshape tensor:\n {Y}")

Random tensor:
 tensor([[0.8447, 0.1229, 0.8633, 0.4499],
        [0.3957, 0.0698, 0.7351, 0.3384],
        [0.2114, 0.1308, 0.2190, 0.2202],
        [0.2657, 0.0906, 0.9552, 0.6718]])
Reshape tensor:
 tensor([[0.8447],
        [0.1229],
        [0.8633],
        [0.4499],
        [0.3957],
        [0.0698],
        [0.7351],
        [0.3384],
        [0.2114],
        [0.1308],
        [0.2190],
        [0.2202],
        [0.2657],
        [0.0906],
        [0.9552],
        [0.6718]])


# Tự động tính Đạo hàm với `autograd`

In [13]:
x = torch.ones(1, requires_grad=True)
print(f"x: {x}")

y = x + 2
print(f"y: {y}")
print(f"y.grad_fn: {y.grad_fn}")

z = 3 * y * y
z.backward()
print(f"Đạo hàm của z theo x: {x.grad}")

x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>)
y.grad_fn: <AddBackward0 object at 0x767c66a65240>
Đạo hàm của z theo x: tensor([18.])


In [14]:
input = torch.ones(5)  # input tensor
label = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
pred = torch.matmul(input, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(pred, label)

In [15]:
print(f"Input:\n {input}")
print(f"Label:\n {label}")
print(f"Parmeters:\n {w}")
print(f"Bias:\n {b}")
print(f"Prediction:\n {pred}")
print(f"Loss: {loss}")

Input:
 tensor([1., 1., 1., 1., 1.])
Label:
 tensor([0., 0., 0.])
Parmeters:
 tensor([[ 0.6818, -0.0486, -0.0656],
        [ 0.1878,  0.6482, -0.2133],
        [ 2.2628,  0.8076, -2.1083],
        [-0.8591, -1.2702,  0.8219],
        [-1.6090, -0.6533,  0.4093]], requires_grad=True)
Bias:
 tensor([-0.7953,  1.5754,  0.6099], requires_grad=True)
Prediction:
 tensor([-0.1310,  1.0592, -0.5460], grad_fn=<AddBackward0>)
Loss: 0.8145386576652527


In [16]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <MulBackward0 object at 0x767b034b3d30>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x767b034b36d0>


In [17]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.1558, 0.2475, 0.1223],
        [0.1558, 0.2475, 0.1223],
        [0.1558, 0.2475, 0.1223],
        [0.1558, 0.2475, 0.1223],
        [0.1558, 0.2475, 0.1223]])
tensor([0.1558, 0.2475, 0.1223])


# Xây dựng Mô hình đầu tiên với `torch.nn`

In [18]:
linear_layer = nn.Linear(in_features=5, out_features=2)
input_tensor = torch.randn(3, 5)
output = linear_layer(input_tensor)

print(f"Input tensor:\n {input_tensor}")
print(f"Input tensor shape: {input_tensor.shape}")

print(f"\nLinear layer: {linear_layer}")
print(f"Linear layer weight: {linear_layer.weight}")
print(f"Linear layer bias: {linear_layer.bias}")

print(f"\nOutput tensor:\n {output}")

Input tensor:
 tensor([[ 2.2980,  1.1567, -0.2147,  1.0374, -0.7035],
        [-0.0819,  0.0683,  0.6757,  0.8377, -0.4310],
        [-0.1782,  0.1071, -1.3826,  1.2273, -1.3974]])
Input tensor shape: torch.Size([3, 5])

Linear layer: Linear(in_features=5, out_features=2, bias=True)
Linear layer weight: Parameter containing:
tensor([[-0.0602,  0.3871, -0.1629,  0.3326,  0.2971],
        [-0.0045,  0.3506, -0.4121, -0.2241, -0.0289]], requires_grad=True)
Linear layer bias: Parameter containing:
tensor([0.1200, 0.2289], requires_grad=True)

Output tensor:
 tensor([[ 0.6005,  0.5005],
        [ 0.1919, -0.2005],
        [ 0.3906,  0.6024]], grad_fn=<AddmmBackward0>)


In [19]:
embedding_layer = nn.Embedding(num_embeddings=10, embedding_dim=3)
input_indices = torch.LongTensor([1, 5, 0, 8])
embeddings = embedding_layer(input_indices)

print(f"Input indices:\n {input_indices}")
print(f"Input tensor shape: {input_indices.shape}")

print(f"\nEmbedding layer: {embedding_layer}")
print(f"Linear layer weight: {embedding_layer.weight}")

print(f"\nOutput embedding:\n {embeddings}")

Input indices:
 tensor([1, 5, 0, 8])
Input tensor shape: torch.Size([4])

Embedding layer: Embedding(10, 3)
Linear layer weight: Parameter containing:
tensor([[-1.2494e-01,  5.2760e-01, -1.6417e-01],
        [-6.0314e-01, -5.1164e-01,  2.8543e+00],
        [-1.5458e+00, -4.7822e-01,  1.4583e+00],
        [ 1.1928e+00, -3.8154e-01, -8.0988e-01],
        [-2.3418e-01, -7.5094e-02,  3.6692e-01],
        [-9.6148e-02,  7.3330e-01,  3.7602e-01],
        [-3.4586e-01,  1.6890e-03,  2.6733e-01],
        [-2.6935e-01,  3.9325e-01, -5.6437e-01],
        [ 1.4046e-01, -8.0245e-01, -1.8078e+00],
        [ 5.0451e-01, -3.5162e-01, -4.0137e-01]], requires_grad=True)

Output embedding:
 tensor([[-0.6031, -0.5116,  2.8543],
        [-0.0961,  0.7333,  0.3760],
        [-0.1249,  0.5276, -0.1642],
        [ 0.1405, -0.8024, -1.8078]], grad_fn=<EmbeddingBackward0>)


In [20]:
class MyEmbeddingModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(MyEmbeddingModel, self).__init__()
        self.embedding = nn.Embedding(num_embeddings=vocab_size, embedding_dim=embedding_dim)
        self.linear = nn.Linear(in_features=embedding_dim, out_features=hidden_dim)
        self.relu = nn.ReLU()
        self.output = nn.Linear(in_features=hidden_dim, out_features=output_dim)

    def forward(self, x):
        embedded = self.embedding(x)
        hiddens = self.relu(self.linear(embedded))
        output = self.output(hiddens)
        return output


model = MyEmbeddingModel(vocab_size=100, embedding_dim=16, hidden_dim=8, output_dim=2)
input_data = torch.LongTensor([[1, 2, 5, 9]])  # một câu gồm 4 từ
output_data = model(input_data)

print(f"Model architecture:\n {model}")
print(f"\nEmbedding layer weight:\n {model.embedding.weight}")
print(f"\n Linear layer weight:\n {model.linear.weight}")
print(f"\n Linear layer bias:\n {model.linear.bias}")
print(f"\nOutput layer weight:\n {model.output.weight}")
print(f"\nOutput layer bias:\n {model.output.bias}")

Model architecture:
 MyEmbeddingModel(
  (embedding): Embedding(100, 16)
  (linear): Linear(in_features=16, out_features=8, bias=True)
  (relu): ReLU()
  (output): Linear(in_features=8, out_features=2, bias=True)
)

Embedding layer weight:
 Parameter containing:
tensor([[-0.7103,  0.3912,  1.9932,  ..., -0.3411,  0.1928, -1.3143],
        [-0.0632, -1.3174,  0.1539,  ..., -1.0970,  1.1928,  0.2997],
        [-0.3892, -1.4749,  0.7311,  ...,  0.7675,  0.7021, -1.2288],
        ...,
        [-1.2847, -0.4262,  0.7513,  ..., -0.9103, -0.1506,  2.9844],
        [ 0.4316,  1.4080, -1.4460,  ..., -0.3130,  0.3060,  0.2113],
        [ 0.1727, -0.1096,  0.6588,  ..., -1.1831,  0.2935, -0.2848]],
       requires_grad=True)

 Linear layer weight:
 Parameter containing:
tensor([[-0.2266, -0.0524, -0.0011, -0.2028, -0.1767,  0.1688,  0.1590, -0.0459,
         -0.1168, -0.0198, -0.1549, -0.1896,  0.0008, -0.0811, -0.0895,  0.2216],
        [ 0.1516, -0.1180,  0.0872,  0.2023,  0.0028,  0.1056, -0.0

In [21]:
print(f"\nInput data: {input_data}")
print(f"Input data shape: {input_data.shape}")
print(f"Output data:\n {output_data}")
print(f"Model output shape: {output_data.shape}")


Input data: tensor([[1, 2, 5, 9]])
Input data shape: torch.Size([1, 4])
Output data:
 tensor([[[-0.1417,  0.0479],
         [ 0.0553,  0.2788],
         [ 0.0731,  0.1633],
         [ 0.4935, -0.0290]]], grad_fn=<ViewBackward0>)
Model output shape: torch.Size([1, 4, 2])
