In [1]:
import numpy as np
import torch
import torch.nn as nn

# Khởi tạo Tensor

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [4]:
x_ones = torch.ones_like(x_data)  # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones}")

x_rand = torch.rand_like(x_data, dtype=torch.float)  # overrides the datatype of x_data
print(f"\nRandom Tensor: \n {x_rand}")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]])

Random Tensor: 
 tensor([[0.8031, 0.0996],
        [0.6547, 0.4113]])


In [5]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4192, 0.2036, 0.0439],
        [0.5843, 0.7676, 0.1499]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
tensor = torch.rand(3, 4)

print(tensor)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

tensor([[0.0284, 0.8052, 0.6165, 0.8051],
        [0.9634, 0.2861, 0.8676, 0.2983],
        [0.7467, 0.3407, 0.7081, 0.6181]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Các phép toán trên Tensor

In [7]:
print(x_data)
print(x_data.dtype)
print(x_data.shape)
print(x_data.device)

tensor([[1, 2],
        [3, 4]])
torch.int64
torch.Size([2, 2])
cpu


In [8]:
tensor_sum = x_data + x_data
print(tensor_sum)

tensor([[2, 4],
        [6, 8]])


In [9]:
tensor_prod = 5 * x_data
print(tensor_prod)

tensor([[ 5, 10],
        [15, 20]])


In [10]:
print(f"Tensor:\n {x_data}")
print(f"Transpose tensor:\n {x_data.T}")

tensor_prod_trans = x_data @ x_data.T
print(f"Result:\n {tensor_prod_trans}")

Tensor:
 tensor([[1, 2],
        [3, 4]])
Transpose tensor:
 tensor([[1, 3],
        [2, 4]])
Result:
 tensor([[ 5, 11],
        [11, 25]])


# Indexing and Slicing

In [11]:
first_row = x_data[0]
print(f"First row: {first_row}")
second_col = x_data[:, 1]
print(f"Second column: {second_col}")
value = x_data[1, 1]
print(f"Value: {value}")

First row: tensor([1, 2])
Second column: tensor([2, 4])
Value: 4


# Thay đổi hình dạng Tensor

In [12]:
X = torch.rand(4, 4)
print(f"Random tensor:\n {X}")
Y = X.reshape((16, 1))
print(f"Reshape tensor:\n {Y}")

Random tensor:
 tensor([[0.6178, 0.9331, 0.6780, 0.6965],
        [0.5465, 0.8181, 0.3849, 0.9848],
        [0.8569, 0.9526, 0.3220, 0.8228],
        [0.4253, 0.3162, 0.7710, 0.7640]])
Reshape tensor:
 tensor([[0.6178],
        [0.9331],
        [0.6780],
        [0.6965],
        [0.5465],
        [0.8181],
        [0.3849],
        [0.9848],
        [0.8569],
        [0.9526],
        [0.3220],
        [0.8228],
        [0.4253],
        [0.3162],
        [0.7710],
        [0.7640]])


# Tự động tính Đạo hàm với `autograd`

In [13]:
x = torch.ones(1, requires_grad=True)
print(f"x: {x}")

y = x + 2
print(f"y: {y}")
print(f"y.grad_fn: {y.grad_fn}")

z = 3 * y * y
z.backward()
print(f"Đạo hàm của z theo x: {x.grad}")

x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>)
y.grad_fn: <AddBackward0 object at 0x77d4b4438880>
Đạo hàm của z theo x: tensor([18.])


In [14]:
input = torch.ones(5)  # input tensor
label = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
pred = torch.matmul(input, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(pred, label)

In [15]:
print(f"Input:\n {input}")
print(f"Label:\n {label}")
print(f"Parmeters:\n {w}")
print(f"Bias:\n {b}")
print(f"Prediction:\n {pred}")
print(f"Loss: {loss}")

Input:
 tensor([1., 1., 1., 1., 1.])
Label:
 tensor([0., 0., 0.])
Parmeters:
 tensor([[-0.2857,  0.0402,  0.7835],
        [-0.4961,  0.4075,  0.2180],
        [ 0.6910,  1.1184, -1.2423],
        [ 0.6037,  0.7890, -1.1845],
        [ 1.1127, -0.9284, -1.5770]], requires_grad=True)
Bias:
 tensor([ 0.5856, -1.0752,  0.0619], requires_grad=True)
Prediction:
 tensor([ 2.2112,  0.3516, -2.9404], grad_fn=<AddBackward0>)
Loss: 1.083675503730774


In [16]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <MulBackward0 object at 0x77d3640fa6b0>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x77d3640f9c00>


In [17]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.3004, 0.1957, 0.0167],
        [0.3004, 0.1957, 0.0167],
        [0.3004, 0.1957, 0.0167],
        [0.3004, 0.1957, 0.0167],
        [0.3004, 0.1957, 0.0167]])
tensor([0.3004, 0.1957, 0.0167])


# Xây dựng Mô hình đầu tiên với `torch.nn`

In [18]:
linear_layer = nn.Linear(in_features=5, out_features=2)
input_tensor = torch.randn(3, 5)
output = linear_layer(input_tensor)

print(f"Input tensor:\n {input_tensor}")
print(f"Input tensor shape: {input_tensor.shape}")

print(f"\nLinear layer: {linear_layer}")
print(f"Linear layer weight: {linear_layer.weight}")
print(f"Linear layer bias: {linear_layer.bias}")

print(f"\nOutput tensor:\n {output}")

Input tensor:
 tensor([[ 1.6003, -2.2417, -1.1308, -1.0873, -0.5396],
        [ 1.2881, -1.5051, -1.3733,  0.7075,  0.3409],
        [ 0.8490,  1.1690, -0.8782,  1.5041,  0.0854]])
Input tensor shape: torch.Size([3, 5])

Linear layer: Linear(in_features=5, out_features=2, bias=True)
Linear layer weight: Parameter containing:
tensor([[-0.1836,  0.1716,  0.2226, -0.2137, -0.2211],
        [ 0.1912, -0.3166,  0.4117, -0.2287, -0.1025]], requires_grad=True)
Linear layer bias: Parameter containing:
tensor([0.2518, 0.0251], requires_grad=True)

Output tensor:
 tensor([[-0.3267,  0.8793],
        [-0.7752, -0.0142],
        [-0.2392, -0.8970]], grad_fn=<AddmmBackward0>)


In [19]:
embedding_layer = nn.Embedding(num_embeddings=10, embedding_dim=3)
input_indices = torch.LongTensor([1, 5, 0, 8])
embeddings = embedding_layer(input_indices)

print(f"Input indices:\n {input_indices}")
print(f"Input tensor shape: {input_indices.shape}")

print(f"\nEmbedding layer: {embedding_layer}")
print(f"Linear layer weight: {embedding_layer.weight}")

print(f"\nOutput embedding:\n {embeddings}")

Input indices:
 tensor([1, 5, 0, 8])
Input tensor shape: torch.Size([4])

Embedding layer: Embedding(10, 3)
Linear layer weight: Parameter containing:
tensor([[ 0.9425, -0.0142,  0.9977],
        [-1.2971, -1.9741, -0.6843],
        [-0.3594,  0.4349,  0.2520],
        [-0.1520, -1.2002, -0.3392],
        [ 0.7016,  0.7317,  0.8861],
        [ 0.1794, -1.0234, -0.6645],
        [ 0.9749,  1.9143, -0.8344],
        [-1.5049,  0.1248, -0.0432],
        [-0.5368, -1.0138, -1.3212],
        [ 0.2018,  0.4852,  0.6916]], requires_grad=True)

Output embedding:
 tensor([[-1.2971, -1.9741, -0.6843],
        [ 0.1794, -1.0234, -0.6645],
        [ 0.9425, -0.0142,  0.9977],
        [-0.5368, -1.0138, -1.3212]], grad_fn=<EmbeddingBackward0>)


In [20]:
class MyEmbeddingModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(MyEmbeddingModel, self).__init__()
        self.embedding = nn.Embedding(num_embeddings=vocab_size, embedding_dim=embedding_dim)
        self.linear = nn.Linear(in_features=embedding_dim, out_features=hidden_dim)
        self.relu = nn.ReLU()
        self.output = nn.Linear(in_features=hidden_dim, out_features=output_dim)

    def forward(self, x):
        embedded = self.embedding(x)
        hiddens = self.relu(self.linear(embedded))
        output = self.output(hiddens)
        return output


model = MyEmbeddingModel(vocab_size=100, embedding_dim=16, hidden_dim=8, output_dim=2)
input_data = torch.LongTensor([[1, 2, 5, 9]])  # một câu gồm 4 từ
output_data = model(input_data)

print(f"Model architecture:\n {model}")
print(f"\nEmbedding layer weight:\n {model.embedding.weight}")
print(f"\n Linear layer weight:\n {model.linear.weight}")
print(f"\n Linear layer bias:\n {model.linear.bias}")
print(f"\nOutput layer weight:\n {model.output.weight}")
print(f"\nOutput layer bias:\n {model.output.bias}")

Model architecture:
 MyEmbeddingModel(
  (embedding): Embedding(100, 16)
  (linear): Linear(in_features=16, out_features=8, bias=True)
  (relu): ReLU()
  (output): Linear(in_features=8, out_features=2, bias=True)
)

Embedding layer weight:
 Parameter containing:
tensor([[ 0.8749, -1.7999, -0.8192,  ..., -1.3092, -0.0522,  0.5582],
        [ 0.5537,  0.5817, -1.7849,  ..., -0.3201,  1.5454,  0.1548],
        [-1.1546, -0.0535, -0.4936,  ...,  0.0157, -0.3744,  1.4172],
        ...,
        [ 0.7713,  1.6334,  1.4887,  ..., -1.5289, -0.8044, -0.5257],
        [-0.9071,  1.7513, -0.0919,  ..., -0.4366,  0.9880, -0.5115],
        [-2.3071,  0.7739,  0.6855,  ...,  1.2375, -0.3032,  0.3141]],
       requires_grad=True)

 Linear layer weight:
 Parameter containing:
tensor([[-0.2132, -0.1813,  0.0147, -0.0376, -0.0598,  0.1064, -0.0018,  0.0485,
          0.0921,  0.0599, -0.1304, -0.0171,  0.2212, -0.1052, -0.0422,  0.0947],
        [ 0.1780, -0.2222,  0.2343, -0.1349, -0.2227, -0.0503,  0.1

In [21]:
print(f"\nInput data: {input_data}")
print(f"Input data shape: {input_data.shape}")
print(f"Output data:\n {output_data}")
print(f"Model output shape: {output_data.shape}")


Input data: tensor([[1, 2, 5, 9]])
Input data shape: torch.Size([1, 4])
Output data:
 tensor([[[ 0.0460, -0.4241],
         [-0.0021, -0.9009],
         [ 0.0413, -0.3359],
         [ 0.1558, -0.3918]]], grad_fn=<ViewBackward0>)
Model output shape: torch.Size([1, 4, 2])
